routes/web.php
<?php

use App\Http\Controllers\Auth\SocialController;
use App\Http\Controllers\Cabinet\CertificateController;
use App\Http\Controllers\Cabinet\CompletedProjectController;
use App\Http\Controllers\Cabinet\ChatController;
use App\Http\Controllers\Cabinet\EventController;
use App\Http\Controllers\Cabinet\ContactController;
use App\Http\Controllers\Cabinet\MainController as CabinetController;
use App\Http\Controllers\Guest\MainController as GuestController;
use App\Http\Livewire\Experts;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\IndexPage;

Route::get('/', IndexPage::class)->name('home');
Route::get('/contact', [GuestController::class, 'contact'])->name('contact');
Route::post('/contact', [GuestController::class, 'messageSend']);
Route::post('/contactUnregistered', [GuestController::class, 'messageUnregisteredSend'])->name('messageUnregisteredSend');

Route::get('/suggest/country', [ContactController::class, 'suggestCountry'])->name('cabinet.suggestCountry');
Route::get('/suggest/city', [ContactController::class, 'suggestCity'])->name('cabinet.suggestCity');

Route::get('/profile/{user?}', [CabinetController::class, 'showProfile'])->name('profile');
Route::get('/impressum', [CabinetController::class, 'impressum'])->name('impressum');
Route::get('/agreement', [GuestController::class, 'getAgreement'])->name('agreement');

Route::group(
    [
        'as' => 'cabinet.',
        'middleware' => ['auth']
    ],
    function () {
        Route::get('/cabinet', [CabinetController::class, 'index'])->name('main');
        Route::get('/experts', Experts::class)->name('experts');
        Route::get('/chat', [ChatController::class, 'index'])->name('chat');
        Route::post('/cabinet', [CabinetController::class, 'cabinetStore']);
        Route::post('/contacts', [ContactController::class, 'contactStore'])->name('contactStore');
        Route::post('/certificate', [CertificateController::class, 'certificateStore'])->name('certificateStore');
        Route::post('/completed-projects', [CompletedProjectController::class, 'projectStore'])->name('projectStore');
        Route::post('/messageSend', [CabinetController::class, 'messageSend'])->name('messageSend');

        Route::get('/suggest/specialities', [CabinetController::class, 'suggestSpecialities'])->name('specialities');
        Route::post('/addAssociation', [CabinetController::class, 'addAssociationMembership'])->name('add.association');
        Route::post('/deleteAssociation', [CabinetController::class, 'deleteAssociationMembership'])->name('delete.association');
        Route::post('/deleteCertificate', [CertificateController::class, 'deleteCertificate'])->name('delete.certificate');
        Route::post('/deleteProject', [CompletedProjectController::class, 'deleteProject'])->name('delete.project');
        Route::post('/avatar', [CabinetController::class, 'avatarStore'])->name('avatar.store');

        Route::get('/events', [EventController::class, 'index'])->name('events');
        Route::get('/event/{event}', [EventController::class, 'show'])->name('event');
        Route::post('/events/store', [EventController::class, 'store'])->name('events.store');

        Route::get('/addToChat/{user}', [CabinetController::class, 'addToChat'])->name('user.addToChat');
        Route::get('/remove-chat/{user}', [CabinetController::class, 'removeChat'])->name('user.removeChat');

        Route::post('/getFriends', [ChatController::class, 'getFriends']);
        Route::post('/session/create', [ChatController::class, 'sessionCreate']);
        Route::post('/session/{session}/chats', [ChatController::class, 'chats']);
        Route::post('/session/{session}/read', [ChatController::class, 'read']);
        Route::post('/session/{session}/clear', [ChatController::class, 'clear']);
        Route::post('/session/{session}/block', [ChatController::class, 'block']);
        Route::post('/session/{session}/unblock', [ChatController::class, 'unblock']);
        Route::post('/send/{session}', [ChatController::class, 'send']);
    }
);

Route::get('/auth/facebook', [SocialController::class, 'facebook'])->name('auth.facebook');
Route::get('/auth/facebook/redirect', [SocialController::class, 'facebookRedirect']);

Route::get('/auth/linkedin', [SocialController::class, 'linkedin'])->name('auth.linkedin');
Route::get('/auth/linkedin/redirect', [SocialController::class, 'linkedinRedirect']);

Route::get('/auth/xing', [SocialController::class, 'xing'])->name('auth.xing');
Route::get('/auth/xing/redirect', [SocialController::class, 'xingRedirect']);

require __DIR__.'/auth.php';

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Http/Controllers/Cabinet/CertificateController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Forms\Cabinet\CertificatesForm;
use App\Http\Controllers\Controller;
use App\Models\Certificate;
use Html;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class CertificateController extends Controller
{
    use FormBuilderTrait;

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Support\HtmlString
     */
    public function certificateStore(Request $request)
    {
        $cert = null;
        $contactsForm = $this->form(CertificatesForm::class);

        if (!$contactsForm->isValid()) {
            return response()->json([
                'error' => $contactsForm->getErrors(),
            ], 400, [], JSON_UNESCAPED_UNICODE);
        }

        $certificateID = $request->input('certificate_id');
        $result = Auth::user()
            ->certificates()
            ->syncWithoutDetaching([$certificateID => ['date' => $request->input('date')]]);

        if (data_get($result, 'attached')) {
            $certificate = Certificate::find($request->input('certificate_id'));
            $cert = Html::tag('li', $certificate->name . Html::tag('a', '', [
                    'id' => 'cert' . $certificate->id,
                    'href' => '',
                    'class' => 'icon-x cert-delete',
                    'data-certid' => $certificate->id,
                ]))->toHtml();
        }

        return response()->json([
            'message' => __('frontend.success'),
            'cert' => $cert
        ]);
    }

    public function deleteCertificate(Request $request)
    {
        if ($request->input('certID')) {
            $result = Auth::user()
                ->certificates()
                ->detach($request->input('certID'));

            if ($result) {
                return response()->json([
                    'deleted' => $request->input('certID'),
                ]);
            }
        }

        return response()->json([
            'error' => 'Return without deleting',
        ], 400, [], JSON_UNESCAPED_UNICODE);
    }
}

app/Http/Controllers/Cabinet/ChatController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Events\Block;
use App\Events\Message;
use App\Events\MessageRead;
use App\Events\SessionEvent;
use App\Http\Controllers\Controller;
use App\Http\Resources\ChatResource;
use App\Http\Resources\SessionResource;
use App\Http\Resources\UserResource;
use App\Models\Chat;
use App\Models\Session;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ChatController extends Controller
{
    public function index()
    {
        return view('cabinet.chat.index');
    }

    /**
     * Get chet friends.
     */
    public function getFriends()
    {
        $newCollection = collect();
        $userFriendsIDs = User::getChatFriends();

        if (!$userFriendsIDs) {
            return [];
        }

        foreach (array_chunk($userFriendsIDs, 100) as $arr_chunk) {
            $newCollection = $newCollection->merge(User::whereIn('id', $arr_chunk)->get());
        }

        return UserResource::collection($newCollection);
    }

    /**
     * Get chet friends.
     * @param Request $request
     * @param Session $session
     */
    public function send(Request $request, Session $session)
    {
        $message = $session->messages()->create([
            'content' => $request->input('message')
        ]);

        if ($message) {
            $chat = $message->createForSend($session->id);
            $message->createForReceive($session->id, $request->to_user);
        }

        Message::dispatch($message->content, $chat);

        return response()->json($chat->id);
    }

    public function chats(Request $request, Session $session)
    {
        $chats = $session->chats()->with('message')->where('user_id', Auth::id())->get();
        return ChatResource::collection($chats);
    }

    /**
     * Create session.
     * @param Request $request
     * @return SessionResource
     */
    public function sessionCreate(Request $request)
    {
        $session = Session::firstOrCreate([
            'user1_id' => Auth::id(),
            'user2_id' => $request->input('friend_id')
        ]);

        $sessionResource = new SessionResource($session);
        SessionEvent::dispatch($sessionResource, Auth::id());
        return $sessionResource;
    }

    /**
     * Read messages.
     * @param Request $request
     * @param Session $session
     */
    public function read(Session $session)
    {
        $chats = $session->chats
            ->whereNull('read_at')
            ->where('type', Chat::SEND)
            ->where('user_id', '!=', Auth::id());

        foreach ($chats as $chat) {
            $chat->update([
                'read_at' => Carbon::now()
            ]);

            MessageRead::dispatch(new ChatResource($chat), $chat->session_id);
        }
    }

    /**
     * Clear all messages.
     * @param Session $session
     * @return \Illuminate\Http\JsonResponse
     */
    public function clear(Session $session)
    {
        $session->deleteChats();

        if (!$session->chats->count()) {
            $session->deleteMessages();
        }

        return response()->json('cleared');
    }

    public function block(Session $session)
    {
        $session->block();
        Block::dispatch($session->id, true);
        return response(null, 201);
    }

    public function unblock(Session $session)
    {
        $session->unblock();
        Block::dispatch($session->id, false);
        return response(null, 201);
    }
}

app/Http/Controllers/Cabinet/CompletedProjectController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Forms\Cabinet\CompletedProjectsForm;
use App\Http\Controllers\Controller;
use App\Models\CompletedProjects;
use Html;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class CompletedProjectController extends Controller
{
    use FormBuilderTrait;

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Support\HtmlString
     */
    public function projectStore(Request $request)
    {
        $cert = null;
        $contactsForm = $this->form(CompletedProjectsForm::class);

        if (!$contactsForm->isValid()) {
            return response()->json([
                'error' => $contactsForm->getErrors(),
            ], 400, [], JSON_UNESCAPED_UNICODE);
        }

        $project = Auth::user()->projects()->create($request->except(['_token']));

        if ($project) {
            $cert = Html::tag('li', $project->name . Html::tag('a', '', [
                    'id' => 'project' . $project->id,
                    'href' => '',
                    'class' => 'icon-x project-delete',
                    'data-projectid' => $project->id,
                ]))->toHtml();
        }

        return response()->json([
            'message' => __('frontend.success'),
            'cert' => $cert
        ]);
    }

    public function deleteProject(Request $request)
    {
        if ($request->input('projectID')) {

            $result = CompletedProjects::where(['id' => $request->input('projectID')])->delete();

            if ($result) {
                return response()->json([
                    'deleted' => $request->input('projectID'),
                ]);
            }
        }

        return response()->json([
            'error' => 'Return without deleting',
        ], 400, [], JSON_UNESCAPED_UNICODE);
    }
}

app/Http/Controllers/Cabinet/ContactController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Forms\Cabinet\ContactsForm;
use App\Http\Controllers\Controller;
use App\Services\MyQueryEngine;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Kris\LaravelFormBuilder\FormBuilderTrait;

class ContactController extends Controller
{
    use FormBuilderTrait;

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function suggestCountry()
    {
        $builder = DB::table('countries');
        $query = new MyQueryEngine($builder);

        return $query->search('namede')
            ->value('id')
            ->make();
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function suggestCity()
    {
        $builder = DB::table('cities');
        $query = new MyQueryEngine($builder);

        return $query->search('ascii')
            ->value('id')
            ->make();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function contactStore(Request $request)
    {
        $contactsForm = $this->form(ContactsForm::class);

        if (!$contactsForm->isValid()) {
            return response()->json([
                'error' => $contactsForm->getErrors(),
            ], 400, [], JSON_UNESCAPED_UNICODE);
        }

        Auth::user()->update($request->except(['_token']));

        return response()->json([
            'message' => __('frontend.success'),
            'name' => Auth::user()->name
        ]);
    }
}

app/Http/Controllers/Cabinet/EventController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Forms\Cabinet\EventForm;
use App\Http\Controllers\Controller;
use App\Models\Event;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use Mapper;

class EventController extends Controller
{
    use FormBuilderTrait;

    public function index()
    {
        $eventForm = $this->form(EventForm::class, [
            'id' => 'event-form',
            'method' => 'POST',
            'url' => route('cabinet.events.store'),
            'novalidate' => 'novalidate',
        ]);

        $events = Event::active()->get();
        return view('cabinet.events.index', compact('eventForm', 'events'));
    }

    public function show(Event $event)
    {
        $address = urlencode($event->getCountryCity() . ', ' . $event->address);
        return view('cabinet.events.show', compact('event', 'address'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $eventForm = $this->form(EventForm::class);

        if (!$eventForm->isValid()) {
            return response()->json([
                'error' => $eventForm->getErrors(),
            ], 400, [], JSON_UNESCAPED_UNICODE);
        }

        Event::create($request->except(['_token', 'daterange', 'image']));

        return response()->json([
            'message' => __('frontend.success'),
            'name' => Auth::user()->name
        ]);
    }
}

app/Http/Controllers/Cabinet/SessionController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use App\Http\Resources\UserResource;
use App\Models\User;
use Auth;

class SessionController extends Controller
{
    /**
     * Create session.
     */
    public function sessionCreate()
    {
        return UserResource::collection(User::where('id', '!=', Auth::id())->get());
    }
}

resources/views/cabinet/events/index.blade.php
@extends('frontend.layouts.app')

@section('header')
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="font-weight-bold">Jetzt die besten Crowd Experten für Ihr Projekt finden</h1>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('sidebar')
    <!-- sidebar -->
    <aside class="overlay">
        <button class="overlay-toggler burger text-black" type="button">
            <span></span>
        </button>
        <div class="overlay-body">
            <div>
                <div class="row">
                    <div class="col">
                        <h2 class="h1 mb-2">Create Event</h2>
                    </div>
                </div>
                {!! form_start($eventForm) !!}
                    <fieldset class="row gutter-2">
                        <div class="col-md-6 col-lg-12">
                            {!! form_row($eventForm->title) !!}
                        </div>
                        <div class="col-md-6 col-lg-12">
                            {!! form_row($eventForm->description) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->facebook_url) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->twitter_url) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->xing_url) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->web_url) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->daterange) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->address) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->country_id) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->city_id) !!}
                        </div>
                        <div class="col-12">
                            {!! form_row($eventForm->image) !!}
                        </div>
                    </fieldset>

                    <div class="overlay-footer">
                        <div>
                            {!! form_widget($eventForm->send) !!}
                        </div>
                    </div>

                {!! form_end($eventForm, false) !!}
            </div>
        </div>

    </aside>
@endsection

@section('content')
    <section class="page-title">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-6">
                    <h1 class="font-weight-bold">Events</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Events</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <ul class="page-options">
                        <li>
                            <button class="btn btn-primary overlay-toggler" type="button">
                                New Event
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <!-- main info -->
    <section class="bg-light">
        <div class="container mt-0">

            <div class="row gutter-md-4 gutter-6">
                @forelse ($events as $event)
                    <div class="col-md-6 col-lg-4">
                        <a href="{{ route('cabinet.event', $event) }}" class="event">
                            <time>{{ optional($event->date_start)->format('d F Y') }}</time>
                            <h2 class="event-title">{{ $event->title }}</h2>
                            <span class="event-location">{{ $event->getCountryCity() }}</span>
                        </a>
                    </div>
                @empty
                    <div class="col-12">
                        <h2 class="font-weight-bold mb-1">No events found.</h2>
                        <p class="lead">Keep checking, more events are coming</p>
                    </div>
                @endforelse
            </div>

{{--            <div class="row">--}}
{{--                <div class="col text-center">--}}
{{--                    <a href="" class="btn btn-outline-primary">Load More</a>--}}
{{--                </div>--}}
{{--            </div>--}}

        </div>
    </section>

    @php Asset::js('/js/cabinet_forms_validate.js') @endphp

@endsection

resources/views/cabinet/events/show.blade.php
@extends('frontend.layouts.app')

@section('content')
    <!-- page title -->
    <section class="page-title">
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-6">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('cabinet.events') }}">Events</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ $event->title }}</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-6 text-lg-right">
                    <ul class="page-options">
                        @livewire('event-add-user', ['event' => $event])
                    </ul>
                </div>
            </div>
        </div>
    </section>


    <section class="bg-light">
        <div class="container mt-0">

            <div class="row gutter-4 gutter-lg-6">
                <div class="col-6 col-md-4 col-lg-3">
                    <figure class="mb-3">
                        <img src="{{ schema_asset($event->getFile('image')) }}" alt="Event Image">
                    </figure>

                </div>
                <div class="col-md-10 col-lg-6">
                    <div class="row">
                        <div class="col">
                            <h1 class="mb-2">{{ $event->title }}</h1>
                            {{ $event->description }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <ul class="meta">
                                @if($event->getCountryCity())
                                    <li>
                                        <span>
                                            <i class="icon-map-pin mr-1"></i>{{ $event->getCountryCity() }}
                                        </span>
                                    </li>
                                @endif
                                @if($event->web_url)
                                    <li>
                                        <a href="{{ $event->web_url }}"><i class="icon-link mr-1"></i></a>
                                    </li>
                                @endif
                                @if($event->facebook_url)
                                    <li>
                                        <a href="{{ $event->facebook_url }}" class="icon-facebook-2"></a>
                                    </li>
                                @endif
                                @if($event->twitter_url)
                                    <li>
                                        <a href="{{ $event->twitter_url }}" class="icon-twitter-2"></a>
                                    </li>
                                @endif
                                @if($event->xing_url)
                                    <li>
                                        <a href="{{ $event->xing_url }}" class="icon-linkedin-2"></a>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 text-lg-right">
                    <ul class="list-group list-group-sm list-group-minimal">
                        <li class="list-group-item">
                            <h5 class="mb-0">{{ $event->date_start->format('d M') }} - {{ $event->date_end->format('d M, Y') }}</h5>
                            <span class="eyebrow text-muted">Date</span>
                        </li>
                        <li class="list-group-item">
                            <h5 class="mb-0">{{ $event->getCountryCity() }}</h5>
                            <span class="eyebrow text-muted">Location</span>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </section>


    <section>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="accordion" id="accordion-1">
                        <div class="card">
                            <div class="card-header" id="heading-1-1">
                                <h2 class="mb-0">
                                    <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                            data-target="#collapse-1-1" aria-expanded="false" aria-controls="collapse-1-1">
                                        Diese Experten Nehmen Teil
                                    </button>
                                </h2>
                            </div>

                            <div id="collapse-1-1" class="collapse" aria-labelledby="heading-1-1" data-parent="#accordion-1">
                                <div class="card-body">
                                    @livewire('event-users', ['event' => $event])
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <div class="card-header" id="heading-1-2">
                                <h2 class="mb-0">
                                    <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                            data-target="#collapse-1-2" aria-expanded="false" aria-controls="collapse-1-2">
                                        Location
                                    </button>
                                </h2>
                            </div>

                            <div id="collapse-1-2" class="collapse" aria-labelledby="heading-1-2" data-parent="#accordion-1">
                                <div id="card-body" class="card-body" style="height: 500px">
                                    <iframe src="https://www.google.com/maps/embed/v1/place?q={{ $address }}&key=AIzaSyDJVbJ6Hx1ujltysxHUZw0PXUakYihUcKA" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @php Asset::js('https://maps.google.com/maps/api/js?key=' .  config('googlmapper.key') ) @endphp
@endsection